### ISSUE TITLE
ERROR: bootstrap checks failed in elasticsearch

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [blacktop/docker-cuckoo#10]
Web interface is unreachable because elastic search docker can't start with the error in the title

this is the last part of the log of docker-compose running without -d

elasticsearch_1  | ERROR: bootstrap checks failed
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2017-04-11T11:26:21,051][INFO ][o.e.n.Node               ] [Bq3e7JX] stopping ...
elasticsearch_1  | [2017-04-11T11:26:21,074][INFO ][o.e.n.Node               ] [Bq3e7JX] stopped
elasticsearch_1  | [2017-04-11T11:26:21,074][INFO ][o.e.n.Node               ] [Bq3e7JX] closing ...
elasticsearch_1  | [2017-04-11T11:26:21,093][INFO ][o.e.n.Node               ] [Bq3e7JX] closed

**Comment by blacktop** [comment]
that is an issue with elasticsearch and can be fixed by running the following:

`sudo sysctl -w vm.max_map_count=262144`
