### ISSUE TITLE
Cannot link to a non running container: /elasticsearch AS /cuckoo-web/elasticsearch.

### ISSUE THREAD

**Issue by Ethonwu** [blacktop/docker-cuckoo#11]
Hi,I use docker version 17.03 and my OS is Ubuntu16.04
When i run 
docker run -d --name cuckoo-web --link mongo --link elasticsearch -p 80:31337 blacktop/cuckoo:2.0 web
command got error
the error message is 
docker: Error response from daemon: Cannot link to a non running container: /elasticsearch AS /cuckoo-web/elasticsearch.
I run your "Usage" page and step by step use your command
This is my first time to build cuckoo environment,and i use MacOS got same result 
Can you suggest me how to do , or some references information thank you very much

**Comment by blacktop** [comment]
can you check `docker logs elasticsearch` it appears to not be running.  Elasticsearch wants at a minimum 2GB of RAM and/or you might need to do this: 

https://github.com/blacktop/docker-elasticsearch-alpine#known-issues-warning

**Comment by Ethonwu** [comment]
So sorry i got a mistake i forgot install yara and volatility 
Now i install that two docker image and alias 
I can successful show web on my Ubuntu computer
But i have some problem 
Cuckoo sandbox use virtual window on system 
Does your cuckoo system need to install kvm or some software to bind ?

**Comment by blacktop** [comment]
I am going to work on integrating with KVM, it currently only supports remote hypervisors.

**Comment by Ethonwu** [comment]
Wow you are so amazing
It's a pity i am not good at Docker can't help you  
Thank you for your project
