### ISSUE TITLE
/entrypoint.sh: cd: line 160: can't cd to /cuckoo/utils

### ISSUE THREAD

**Issue by symnoisy** [blacktop/docker-cuckoo#12]
Hi, I am a master student in Korea. 

I want to use your docker images, but it didn't work well. 

'cuckoo_api' was dead 
("/entrypoint.sh: cd: line 160: can't cd to /cuckoo/utils")

look at the bellow: (this snapshot was captured by my Macbook Pro, but it is occured my ubuntu server also)

<img width="1084" alt="1__bash" src="https://cloud.githubusercontent.com/assets/9783553/25370402/79c70f78-29c5-11e7-9a90-d71831536c7f.png">

Tell me how to fix this

Sincerely regards.

**Comment by blacktop** [comment]
I believe I have corrected the issue

**Comment by blacktop** [comment]
Please **note:**

> :construction: WARNING: Currently only works with remote machinery: **esx, vsphere and xenserver**.

**Comment by blacktop** [comment]
I hopefully this weekend will get it to work with at least Virtualbox VMs as well

**Comment by symnoisy** [comment]
Thank you for reply quickly, I want to use it (I really hope so)...

by the way, May I use your docker images to my paper (of course I reference your github link to my paper)

because I am designing scalability malware identification framework, I need it ! 

May I use your images in my paper?

**Comment by blacktop** [comment]
Yes of course you can use my images.  They all have a MIT license.  Thank you.

**Comment by symnoisy** [comment]
Hi, Can you tell me progress? If you need help, I can help you!

**Comment by blacktop** [comment]
Yes, you can help.  Can you figure out how to run windows in KVM in docker?

**Comment by symnoisy** [comment]
Sure ! so I try it and tell you how to run !
