### ISSUE TITLE
VM doesn't start

### ISSUE THREAD

**Issue by nicolasraus** [blacktop/docker-cuckoo#13]
Hi, I'm trying to get it work on a esxi. I've made the following changes https://github.com/NicolasRaus/docker-cuckoo/commit/4dfe540b013e2ad3227607485850756a4fc27ff0
but it isn't working, when I submit a file from the web it stays in pending and keeps refreshing it but nothing happens. And the virtual machine doesn't seem to be running. In the logs I get following "errors"
![screenshot 92](https://cloud.githubusercontent.com/assets/2265697/25550131/fff5dbf4-2c4c-11e7-9dd3-4f5083638c89.jpg)
![screenshot 93](https://cloud.githubusercontent.com/assets/2265697/25550135/fffaa9c2-2c4c-11e7-8915-0a348b17c880.jpg)
![screenshot 94](https://cloud.githubusercontent.com/assets/2265697/25550133/fff70330-2c4c-11e7-99aa-dfb31df7b233.jpg)
![screenshot 95](https://cloud.githubusercontent.com/assets/2265697/25550134/fff86e00-2c4c-11e7-8840-e3a414a619df.jpg)
![screenshot 96](https://cloud.githubusercontent.com/assets/2265697/25550132/fff668d0-2c4c-11e7-9c96-5a240bee3b44.jpg)
![screenshot 97](https://cloud.githubusercontent.com/assets/2265697/25550255/ffd0e212-2c4d-11e7-918e-96d2489af55d.jpg)
Also the cuckoo.conf file seems to be modified when cuckoo starts.
Do you know what should I do? Any ideas?

**Comment by blacktop** [comment]
So I look for the env var `RESULTSERVER` to be set and if it isn't I set it to `0.0.0.0` and update the config to reflect that.  I see though that you set it in the config to `0.0.0.0` so it should be changing it to the same thing it already is?

**Comment by blacktop** [comment]
Also it looks like you are disabling **elasticsearch** in the docker-compose.yml, but ARE enabling it in the `cuckoo.conf` ?

**Comment by blacktop** [comment]
Also maybe you know more than I do on this topic, but you are pulling fields from `reporting.conf` into `cuckoo.conf` ?

**Comment by blacktop** [comment]
I wonder if the things you have in `2.0/conf/cuckoo.conf` are clobbering the others you have in `reporting.conf` etc etc?  I haven't looked at how cuckoo combines it config files in a while

**Comment by blacktop** [comment]
When you submitted the sample I would curious as to what `docker-compose logs cuckoo` displayed.  That would probably have the logs corresponding to cuckoo talking to ESXi.

I am very interested in knowing if this works.  I don't personally have access to ESXi :(

**Comment by blacktop** [comment]
Also what do you see when you curl the API for this: http://docs.cuckoosandbox.org/en/latest/usage/api/#machines-list

**Comment by nicolasraus** [comment]
Hey! I curl the API for machines/list and I get:
{
  "machines": []
}
do you know why?

and also:

> Also maybe you know more than I do on this topic, but you are pulling fields from reporting.conf into cuckoo.conf ?

It seems that reporting.conf is being appended at the top of cuckoo.conf automatically when I run docker-compose up. I don't know why.

**Comment by nicolasraus** [comment]
And also you were right I left elsticsearch enabled on cuckoo.conf but I'm not using it so I turned it off now on cuckoo.conf

**Comment by blacktop** [comment]
I have updated the way I try to update conf files, hopefully that will stop overwriting?

**Comment by nicolasraus** [comment]
Pull request [#16](https://github.com/blacktop/docker-cuckoo/pull/16) fixed my issue.
What happened was that api container was saving tasks on sqlite file, which wasn't shared with cuckoo's container

**Comment by blacktop** [comment]
I'm glad that it is working and glad @kdeltared made the pull request
