### ISSUE TITLE
Setup network in cuckoo docker

### ISSUE THREAD

**Issue by toantv90** [blacktop/docker-cuckoo#14]
I've installed docker for cuckoo 2.0. But I have some issue with network setup for the guest machine and cuckoo docker. 
Can you help me? 
- With guest machine: how to setup gateway to cuckoo docker.
- With cuckoo docker: how to sniffer network.
`
Failed to start sniffer (interface=eth0, host=172.22.0.100, pcap=/home/cuckoo/storage/analyses/13/dump.pcap)
`

**Comment by blacktop** [comment]
What `machinery` are you using?

**Comment by toantv90** [comment]
I'm using vmware. And I have a network:

- Cuckoo network create by cuckoo: 172.18.0.0/16
- Vmware Nat network: 192.168.100.0/24
I need route all traffic from vmare network to cuckoo network?
Is there any other idea?

**Comment by toantv90** [comment]
I'm using cuckoo docker with network_mode==host

>  network_mode: "host"

And I solved it. But I would like to hear your opinion about this.

**Comment by blacktop** [comment]
are you able to submit samples to vmware with that network setting?

**Comment by toantv90** [comment]
Yes I'am.
But want to know how you configured the network? I don't see it in your guide.

**Comment by blacktop** [comment]
Can you tell me what VMWare product are you using?

**Comment by blacktop** [comment]
Are you using VMWare ESXi?

**Comment by toantv90** [comment]
I'm using VMware workstation, not VMWare ESXi.
I already made plans for VMWare ESXi, but I don't sure it support memory dumps.
What do you using virtual machine? And your solution for network, for memory dumps.
