### ISSUE TITLE
Coudn't find env file

### ISSUE THREAD

**Issue by nov3mb3r** [blacktop/docker-cuckoo#21]
Followed your installation guide but when I run `docker-compose-up -d` 
it appears there is a problem.
`ERROR: Couldn't find env file: /home/username/2.0/config-file.env. `

**Comment by falcorocks** [comment]
same here

**Comment by joanbono** [comment]
Hi @nmantas @falcorocks 

Do the following:

~~~bash
git clone https://github.com/blacktop/docker-cuckoo
cd docker-cuckoo
docker-compose-up -d
~~~
