### ISSUE TITLE
Cuckoo Daemon Not Started by Docker Compose

### ISSUE THREAD

**Issue by hop-dev** [blacktop/docker-cuckoo#3]
The daemon is not started by the docker compose file. Is this intentional?

**Comment by blacktop** [comment]
So when you enable the daemon this happens:

``` bash
Attaching to dockercuckoo_cuckoo_1
cuckoo_1         |
cuckoo_1         |            _______                   _____                    _____
cuckoo_1         |           /::\    \                 /\    \                  /\    \
cuckoo_1         |          /::::\    \               /::\____\                /::\    \
cuckoo_1         |         /::::::\    \             /::::|   |               /::::\    \
cuckoo_1         |        /::::::::\    \           /:::::|   |              /::::::\    \
cuckoo_1         |       /:::/~~\:::\    \         /::::::|   |             /:::/\:::\    \
cuckoo_1         |      /:::/    \:::\    \       /:::/|::|   |            /:::/  \:::\    \
cuckoo_1         |     /:::/    / \:::\    \     /:::/ |::|   |           /:::/    \:::\    \
cuckoo_1         |    /:::/____/   \:::\____\   /:::/  |::|___|______    /:::/    / \:::\    \
cuckoo_1         |   |:::|    |     |:::|    | /:::/   |::::::::\    \  /:::/    /   \:::\ ___\
cuckoo_1         |   |:::|____|     |:::|    |/:::/    |:::::::::\____\/:::/____/  ___\:::|    |
cuckoo_1         |    \:::\    \   /:::/    / \::/    / ~~~~~/:::/    /\:::\    \ /\  /:::|____|
cuckoo_1         |     \:::\    \ /:::/    /   \/____/      /:::/    /  \:::\    /::\ \::/    /
cuckoo_1         |      \:::\    /:::/    /                /:::/    /    \:::\   \:::\ \/____/
cuckoo_1         |       \:::\__/:::/    /                /:::/    /      \:::\   \:::\____\
cuckoo_1         |        \::::::::/    /                /:::/    /        \:::\  /:::/    /
cuckoo_1         |         \::::::/    /                /:::/    /          \:::\/:::/    /
cuckoo_1         |          \::::/    /                /:::/    /            \::::::/    /
cuckoo_1         |           \::/____/                /:::/    /              \::::/    /
cuckoo_1         |            ~~                      \::/    /                \::/____/
cuckoo_1         |                                     \/____/
cuckoo_1         |                                                        it's Cuckoo!
cuckoo_1         |
cuckoo_1         |  Cuckoo Sandbox 2.0-dev
cuckoo_1         |  www.cuckoosandbox.org
cuckoo_1         |  Copyright (c) 2010-2015
cuckoo_1         |
cuckoo_1         | 2016-08-31 21:36:38,214 [root] CRITICAL: CuckooCriticalError: Unable to bind ResultServer on 192.168.56.1:2042: [Errno 99] Address not available
cuckoo_1         |  Checking for updates...
cuckoo_1         |  Outdated! Cuckoo Sandbox version 2.0-rc1 is available now.
```

This is because the config files are **not** set up right.  I will add some more docs and get that part working this weekend hopefully.  I need to figure out what the `ResultServer on 192.168.56.1:2042` will be for everyone using this compose file.

Thank you for bringing this to my attention again.

You might be able to figure this out before I do, you can mount your own config into the daemon by adding:

``` yaml
services:
  cuckoo:
    image: blacktop/cuckoo:2.0
    command: daemon
    volumes:
      - ./conf:/cuckoo/conf
    networks:
      - cuckoo
```

**Comment by hop-dev** [comment]
I solved this by changing the resultserver ip to 0.0.0.0 in the config, however this means that the user will have to configure their respective machinery to point at the external IP of the docker host for the resultserver.

I dont think that anybody will ever be able to use this out-of-the-box without changing the conf files for machinery, so would it be reasonable to mount the conf directory by default?

**Comment by blacktop** [comment]
@hoppers2k9 that is great work! Do you have an ESXi cluster to test with?

**Comment by hop-dev** [comment]
No I use XenServer, so trying to get that working at the moment.

I've noticed they are about to change the installation method, so we may have some work to do soon...

https://github.com/cuckoosandbox/cuckoo/pull/863

**Comment by blacktop** [comment]
haha that is awesome! I wonder if @jbremer looks at any of my stuff? That is how I designed the **docker-entrypoint.sh** to work and how I do **config** with my [malice](https://github.com/maliceio/malice) project.  Or maybe I have just been following all the **cuckoo** bad asses for so long I am just starting to think like them?

**Comment by blacktop** [comment]
Also @jbremer and @botherder, I would love to help out with any DevOpsy stuff and if you see any value in this docker image I would love for it to become part of the cuckoo project some day.

**Comment by blacktop** [comment]
@hoppers2k9 XenServer is an awesome choice I am very interested in trying that out as well.  I need some linux metal first though??

**Comment by hop-dev** [comment]
I used an old laptop :)

**Comment by blacktop** [comment]
Did you get it to work on XenServer?

**Comment by hop-dev** [comment]
No : / got an esxi trial instead, which is much better with the pyvmomi lib

**Comment by blacktop** [comment]
nice! I want to set up an ESXi cluster at work to try it out on, but the people who have access to it don't like to share :'(
