### ISSUE TITLE
image usage in docker-compose.vbox.yml

### ISSUE THREAD

**Issue by ghost** [blacktop/docker-cuckoo#30]
Hi, 
Several issues here:

I cannot get either of the docker-compose files to work with elasticsearch < 6.0. I have modified my local file to use 6.2.2 which seems to work. 

The next barrier is a failure to load the cuckoo python packages. This is only if using the vbox image for the services.

![image](https://user-images.githubusercontent.com/37487040/37636626-5f7add54-2bc0-11e8-8209-22ba54b5cf92.png)

If I edit the docker-compose.vbox.yml to use blacktop/cuckoo:2.0 image, the web interface works. The vbox webservice still fails. 

It looks like when targeting the blacktop/cuckoo:vbox image cuckoo is not getting installed properly, could this have something to do with the virtualenvs?

**Comment by ilyaglow** [comment]
Elasticsearch image from blacktop and `elasticsearch:5-alpine` (deprecated) seems to work just fine for me.

Can confirm that `blacktop/cuckoo:vbox` is failing on `DistributionNotFound` error, but unfortunately I hadn’t time to find our the problem cause. Need help here.

**Comment by pooki3bear** [comment]
It could have something to do with the commits made by blacktop in the meantime. Your original commit built directly and he patched to use blacktop/cuckoo:vbox in commit 83fb35faf613ddaea9e98128e212d4a3af6372c5. 

In commit 976f547c8b11f3da73587247a125290ab8fdb53b he changed the /conf/ copy directories as well.

Can you please submit a standalone environment that works per your build instructions at https://github.com/blacktop/docker-cuckoo/blob/master/docs/virtualbox.md ?

If you can resubmit this, I would REALLY appreciate it. I will be more than happy to help test dev builds against my ubuntu 16 environment.

**Comment by blacktop** [comment]
@ilyaglow doesn't seem to make sense? Maybe an issue with installing your pull request on top of the 2.0.5.1 version?

**Comment by blacktop** [comment]
Does cuckoo support elasticsearch 6+ ?

They are using the 5.3 python client: https://github.com/cuckoosandbox/cuckoo/blob/master/setup.py#L191

**Comment by blacktop** [comment]
If you switch to the tag `2.0` you are not longer using @ilyaglow 's magic sauce vbox stuff so it of course will stop working.

**Comment by ghost** [comment]
Ok, I guess it's up to @ilyaglow to fix the cuckoo install on his vbox image.

**Comment by ilyaglow** [comment]
Sorry for the delay folks!

I debugged the issue and it seems that cuckoo container fails because we do `LDFLAGS=-L/lib pip install -e .` from the pull request source which somehow do not add Cuckoo distribution package to the system. And even if we run this command after the `pip install cuckoo` the container still fails with the same message.

I got success with running cuckoo container using my own [Dockerfile](https://github.com/ilyaglow/docker-cuckoo/blob/vbox-webservice-machinery/virtualbox-webservice-machinery/Dockerfile) that patches already installed Cuckoo in a dirty way. So you can use it as a workaround.

I hope soon we won't need this tricky stuff anymore.

**Comment by whavey** [comment]
I rebuilt the image using the Dockerfile (fix mentioned above) and that works for the distribution not found error but now I am getting an error saying "an unknown machinery has been chosen (machinery=virtualbox_websrv)". Did the cuckoo code changes to allow for the new machinery not make it into the image yet?
