### ISSUE TITLE
Cuckoo 2.0rc2 support

### ISSUE THREAD

**Issue by hop-dev** [blacktop/docker-cuckoo#5]
As per:

https://cuckoo.sh/docs/installation/host/installation.html#install-cuckoo

The way that cuckoo is installed has changed. How do you want to go about supporting this while keeping support for 1.2?

... it would also be good to talk about config generation some time.

**Comment by blacktop** [comment]
to support the 2.0-r2 all I do is create another folder which maps to a docker image tag in DockerHUB

**Comment by blacktop** [comment]
I created the folder, but haven't started on it yet.  Right now it is just a clone of the 2.0 folder.  2.0 seems to be in a lot of flux also I have a co-worker that tried to use it (not in docker, but just a plain install) and said it had a 'lot' of problems.  So it probably makes more sense to make sure 1.2 is working and solid, until official cuckoo 2.0 is more stable-ish?

**Comment by blacktop** [comment]
It is really confusing because the old way still works and what I am going to do is just make 2.0 the latest and greatest version of 2.0-*.

It seems to be working now, but I don't have any remote guests I can test with.  Can you?
