### ISSUE TITLE
 could not translate host name "postgres" to address: Name does not resolve

### ISSUE THREAD

**Issue by gongqihunan** [blacktop/docker-cuckoo#6]
I follow https://hub.docker.com/r/blacktop/cuckoo/,and to install my docker-cuckoo. 
but there have some problems and there is also some problem to link the conf folder ....
could you help me ?
![1](https://cloud.githubusercontent.com/assets/18669930/19923928/a58377b6-a124-11e6-9aab-247af4fa057e.png)
![2](https://cloud.githubusercontent.com/assets/18669930/19923929/a58420bc-a124-11e6-95f0-ef4db3f5b46b.png)

**Comment by blacktop** [comment]
You can see a way to get the daemon to work in issue #3 and it looks like you already have a docker container bound to port 8000 running.  You should clear them out by running

```
docker kill $(docker ps -q); docker rm `docker ps -a -q -f status=exited`
```

and/or

```
docker kill $(docker ps -q); docker rm `docker ps -a -q -f status=created`
```

please note that the docker container only supports these machineries currently: **esx, vsphere and xenserver**

I think I can add the non-remote hypervisors, but need more time... much more time ;) #FOSSLife

**Comment by gongqihunan** [comment]
ah..Thank you indeed~ It's work!

**Comment by gongqihunan** [comment]
what's your idea to run VirtualBox, VMWare Workstation/Fusion or KVM/qemu 0.0

**Comment by blacktop** [comment]
This is my idea - https://github.com/blacktop/vm-proxy I might have time to do it too over the holidays.
